export interface Product {
  id: number
  name: string
  price: number
  description: string
  image: string
  category: "indoor" | "outdoor" | "succulent"
  difficulty: "easy" | "medium" | "hard"
  waterNeeds: "low" | "medium" | "high"
  careInfo: string
}

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Monstera Deliciosa",
    price: 45,
    description: "Popular indoor plant with striking leaves",
    image: "/monstera-deliciosa-plant.jpg",
    category: "indoor",
    difficulty: "easy",
    waterNeeds: "medium",
    careInfo: "Prefers bright, indirect light. Water when soil is dry to touch.",
  },
  {
    id: 2,
    name: "Snake Plant",
    price: 35,
    description: "Low-maintenance air purifying plant",
    image: "/snake-plant-indoor.jpg",
    category: "indoor",
    difficulty: "easy",
    waterNeeds: "low",
    careInfo: "Thrives in low light. Water sparingly, only when soil is dry.",
  },
  {
    id: 3,
    name: "Pothos Plant",
    price: 28,
    description: "Trailing plant perfect for shelves",
    image: "/pothos-plant-hanging.jpg",
    category: "indoor",
    difficulty: "easy",
    waterNeeds: "medium",
    careInfo: "Adaptable to various light conditions. Keep soil moist but not waterlogged.",
  },
  {
    id: 4,
    name: "Peace Lily",
    price: 38,
    description: "Elegant white flowering indoor plant",
    image: "/peace-lily-plant.jpg",
    category: "indoor",
    difficulty: "medium",
    waterNeeds: "medium",
    careInfo: "Prefers moderate to low indirect light. Keep soil moist.",
  },
  {
    id: 5,
    name: "ZZ Plant",
    price: 42,
    description: "Glossy-leafed tropical plant",
    image: "/zz-plant-indoor.jpg",
    category: "indoor",
    difficulty: "easy",
    waterNeeds: "low",
    careInfo: "Extremely tolerant of low light. Water only when soil is dry.",
  },
  {
    id: 6,
    name: "Fiddle Leaf Fig",
    price: 55,
    description: "Statement plant with large leaves",
    image: "/fiddle-leaf-fig-plant.jpg",
    category: "indoor",
    difficulty: "hard",
    waterNeeds: "medium",
    careInfo: "Prefers bright indirect light. Water when top inch of soil is dry.",
  },
  {
    id: 7,
    name: "Aloe Vera",
    price: 25,
    description: "Hardy succulent with healing properties",
    image: "/aloe-vera-succulent.jpg",
    category: "succulent",
    difficulty: "easy",
    waterNeeds: "low",
    careInfo: "Loves sunlight. Water sparingly, allow soil to dry between waterings.",
  },
  {
    id: 8,
    name: "Jade Plant",
    price: 32,
    description: "Succulent with thick, glossy leaves",
    image: "/jade-plant-succulent.jpg",
    category: "succulent",
    difficulty: "easy",
    waterNeeds: "low",
    careInfo: "Requires bright light. Water thoroughly but infrequently.",
  },
  {
    id: 9,
    name: "Money Plant",
    price: 30,
    description: "Brings prosperity and positivity",
    image: "/money-plant-indoor.jpg",
    category: "indoor",
    difficulty: "easy",
    waterNeeds: "medium",
    careInfo: "Prefers indirect light. Water when soil surface feels dry.",
  },
  {
    id: 10,
    name: "Bamboo Palm",
    price: 48,
    description: "Tropical palm plant for larger spaces",
    image: "/bamboo-palm-indoor.jpg",
    category: "indoor",
    difficulty: "medium",
    waterNeeds: "medium",
    careInfo: "Prefers moderate to bright light. Keep soil consistently moist.",
  },
  {
    id: 11,
    name: "Echeveria",
    price: 22,
    description: "Beautiful rosette-shaped succulent",
    image: "/echeveria-succulent.jpg",
    category: "succulent",
    difficulty: "easy",
    waterNeeds: "low",
    careInfo: "Needs bright light. Water only when soil is completely dry.",
  },
  {
    id: 12,
    name: "Rubber Plant",
    price: 52,
    description: "Dramatic plant with deep glossy leaves",
    image: "/rubber-plant-indoor.jpg",
    category: "indoor",
    difficulty: "medium",
    waterNeeds: "medium",
    careInfo: "Prefers bright indirect light. Water when top inch of soil is dry.",
  },
]
